[project]
authors = [{name = "femtomc", email = "mccoybecker@gmail.com"}]
dependencies = []
description = "Add a short description here"
name = "jaxmax"
requires-python = ">= 3.11"
version = "0.1.0"

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi.project]
channels = ["conda-forge", "https://conda.modular.com/max", "https://repo.prefix.dev/modular-community"]
platforms = ["osx-arm64"]

[tool.pixi.pypi-dependencies]
jaxmax = { path = ".", editable = true }

[tool.pixi.tasks]

[tool.pixi.dependencies]
max = "~=24.6"
beartype = ">=0.19.0,<0.20"
jax = ">=0.4.35,<0.5"
pytest = ">=8.3.4,<9"
