name: Run tests and upload coverage

on: 
  push

jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install magic
        run: curl -ssL https://magic.modular.com/deb1dd50-9fef-4d30-98ca-17cb32e01408 | bash
      
      - name: Install kernels
        run: magic run kernels

      - name: Run tests
        run: magic run coverage

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}